// Bundles the extension into one CommonJS file, dist/extension.js, and the TS
// server plugin into another, node_modules/reactogenic-typescript-plugin/index.js;
// with --test, the editor suites too (dist/test/*.js, run inside VS Code).
//
//   node scripts/build.mjs [--production] [--test]
//
// Also writes dist/ThirdPartyNotices.txt: the grammar's notices plus the
// licence of every npm package that is in the extension's bundle (the
// plugin's holds none: the build fails if it does).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
/** The plugin's name: `typescriptServerPlugins` in package.json names it, and tsserver loads it by it. */
export const PLUGIN = "reactogenic-typescript-plugin";

export async function build({ production = false, test = false } = {}) {
  const common = {
    absWorkingDir: root,
    bundle: true,
    format: "cjs",
    platform: "node",
    target: "node20", // the extension host of VS Code 1.91, the floor
    sourcemap: !production,
    sourcesContent: false,
    logLevel: "warning",
  };
  const result = await esbuild.build({
    ...common,
    entryPoints: ["src/extension.ts"],
    outfile: "dist/extension.js",
    external: ["vscode"],
    minify: production,
    metafile: true,
  });
  fs.writeFileSync(path.join(root, "dist/ThirdPartyNotices.txt"), notices(Object.keys(result.metafile.inputs)));

  // The TS server plugin (ide.md, *The plugin*): a package of its own, which
  // tsserver finds by name in the extension's node_modules — in this folder
  // for a run from the checkout, and at the same path in the .vsix.
  const plugin = await esbuild.build({
    ...common,
    entryPoints: ["src/plugin/index.ts"],
    outfile: `node_modules/${PLUGIN}/index.js`,
    target: "node18", // tsserver may run on the user's own Node
    footer: { js: "module.exports = module.exports.default;" }, // tsserver calls the module itself
    sourcemap: false,
    minify: production,
    metafile: true,
  });
  const foreign = Object.keys(plugin.metafile.inputs).filter((input) => input.includes("node_modules/"));
  if (foreign.length > 0) {
    throw new Error(`the plugin has no dependencies, and its bundle holds ${foreign.join(", ")}`);
  }
  const manifest = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
  const pluginManifest = {
    name: PLUGIN,
    version: manifest.version,
    private: true,
    description: "TypeScript server plugin of the Reactogenic extension: .rtsx modules for tsserver.",
    license: "MIT",
    main: "index.js",
  };
  fs.writeFileSync(path.join(root, "node_modules", PLUGIN, "package.json"), `${JSON.stringify(pluginManifest, null, 2)}\n`);

  if (test) {
    await esbuild.build({
      ...common,
      entryPoints: ["trusted", "untrusted", "monorepo", "transpiled", "typescript"].map((suite) => `test/editor/${suite}.ts`),
      outdir: "dist/test",
      external: ["vscode", "mocha"],
      sourcemap: "inline",
    });
  }
  return result.metafile.outputs["dist/extension.js"].bytes;
}

/** The grammar's notices (generated by grammar/generate.mjs), then one section per bundled package. */
function notices(inputs) {
  const packages = new Map();
  for (const input of inputs) {
    const at = input.lastIndexOf("node_modules/");
    if (at < 0) {
      continue;
    }
    const [scope, name] = input.slice(at + "node_modules/".length).split("/");
    const dir = path.join(root, input.slice(0, at), "node_modules", scope.startsWith("@") ? `${scope}/${name}` : scope);
    const manifest = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
    packages.set(`${manifest.name}@${manifest.version}`, { dir, manifest });
  }
  const sections = [fs.readFileSync(path.join(root, "ThirdPartyNotices.txt"), "utf8").trimEnd()];
  for (const [id, { dir, manifest }] of [...packages].sort(([a], [b]) => a.localeCompare(b))) {
    const file = fs.readdirSync(dir).find((f) => /^licen[cs]e(\.(txt|md))?$/i.test(f));
    if (!file) {
      throw new Error(`${id} is in the bundle and has no licence file`);
    }
    const url = typeof manifest.repository === "string" ? manifest.repository : (manifest.repository?.url ?? "");
    const rule = "=".repeat(72);
    const head = [rule, `${id} (${manifest.license}), bundled in dist/extension.js`, ...(url ? [url] : []), rule];
    sections.push([...head, "", fs.readFileSync(path.join(dir, file), "utf8").trim()].join("\n"));
  }
  return `${sections.join("\n\n")}\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const bytes = await build({ production: process.argv.includes("--production"), test: process.argv.includes("--test") });
  console.log(`dist/extension.js ${(bytes / 1024).toFixed(1)} KiB`);
}
